---
name: github.event test
on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  pull-requests: read
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  get-ref:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    steps:
      - name: Get Ref
        id: get-ref
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          set -xv
          gh pr list --state open --json headRefName
