---
name: github.event test
on:
  push:
    tags:
      - 'v[0-9]*'
  workflow_dispatch:
    inputs:
      tag:
        type: string
        description: 'Input tag (e.g. v1.0.1)'
        required: true
permissions:
  id-token: write
  contents: write
  pull-requests: read
defaults:
  run:
    shell: bash
concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true
jobs:
  get-ref:
    runs-on: ubuntu-latest
    timeout-minutes: 1
    outputs:
      ref: ${{ steps.get-ref.outputs.ref }}
    steps:
      - name: Checkout
        uses: actions/checkout@b4ffde65f46336ab88eb53be808477a3936bae11 # v4.1.1
        with:
          fetch-depth: 0
          fetch-tags: true
      - name: Get Ref
        id: get-ref
        run: |
          set -xv
          echo ${{ github.event.payload }}
          git tag
          git log | head
          ref=$(git rev-parse HEAD)
          echo "ref=$ref" >> "$GITHUB_OUTPUT"
